CREATE TYPE electionMode AS ENUM (
  'raffle',
  'majority'
);

CREATE TABLE "settings" (
  "id" integer PRIMARY KEY NOT NULL DEFAULT 0,
  "database_version" integer NOT NULL DEFAULT 0
);

CREATE TABLE "updates" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "file_name" text
);

CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "discord_id" integer UNIQUE NOT NULL,
  "team" integer
);

CREATE TABLE "team" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text DEFAULT 'NULL',
  "subtitle" text DEFAULT 'NULL',
  "color" text DEFAULT '#888888',
  "icon" text DEFAULT '❔'
);

CREATE TABLE "election" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" text DEFAULT 'NULL',
  "subtitle" text DEFAULT '',
  "color" text default '#888888',
  "display_start" timestamp DEFAULT (now()),
  "display_end" timestamp DEFAULT (now() + interval '7 days'),
  "vote_start" timestamp DEFAULT (now() + interval '5 days'),
  "vote_end" timestamp DEFAULT (now() + interval '6 days'),
  "mode" electionMode DEFAULT 'raffle',
  "votes_per_user" integer DEFAULT 3
);

CREATE TABLE "item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text DEFAULT 'NULL',
  "description" text DEFAULT 'NULL',
  "color" text DEFAULT '#888888',
  "icon" text DEFAULT '❔',
  "election" integer,
  "winner" integer
  );

CREATE TABLE "vote" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user" integer,
  "election" integer,
  "item" integer,
  "team" integer
);

CREATE INDEX ON "user" ("discord_id");

CREATE INDEX ON "item" ("winner");

CREATE INDEX ON "item" ("election");

CREATE INDEX ON "vote" ("item");

ALTER TABLE "user" ADD FOREIGN KEY ("team") REFERENCES "team" ("id");

ALTER TABLE "item" ADD FOREIGN KEY ("election") REFERENCES "election" ("id");

ALTER TABLE "item" ADD FOREIGN KEY ("winner") REFERENCES "team" ("id");

ALTER TABLE "vote" ADD FOREIGN KEY ("user") REFERENCES "user" ("id");

ALTER TABLE "vote" ADD FOREIGN KEY ("election") REFERENCES "election" ("id");

ALTER TABLE "vote" ADD FOREIGN KEY ("item") REFERENCES "item" ("id");

ALTER TABLE "vote" ADD FOREIGN KEY ("team") REFERENCES "team" ("id");

-- Set Update Version to Zero
INSERT INTO "settings" (id, database_version) VALUES (0, 0)